name: Selenium and TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Cache Maven dependencies
          uses: actions/cache@v4
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
             ${{ runner.os }}-m2

        - name: Install dependencies
          run: mvn install

        - name: Run tests
          run: |
            xvfb-run mvn clean test -DsuiteXmlFile=testng.xml \
              -Dbrowser=chrome \
              -DenableBrowserOptions=true \
              -Dmaven.test.failure.ignore=true

        - name: Upload Surefire Test Reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: surefire-reports
            path: target/surefire-reports/

        - name: Upload Extent Reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: extent-reports
            path: target/*.html